### PR TITLE
Add runtime dependency to commons-logging.

### PR DESCRIPTION
**Pull request by jgonian**
Fixes https://github.com/arktekk/sbt-aether-deploy/issues/56

### CODE REVIEW

**Comment by hamnis** [comment]
thanks

**Comment by jgonian** [comment]
no problem! Is it possible to publish a bugfix release e.g. `0.22.1`?

**Comment by hamnis** [comment]
Released `0.22.1`, should soon be in maven central

**Comment by jgonian** [comment]
thanks!

**Pull request merged**
