### PR TITLE
changing settings naming and fixing artifact coordinates for scalaJS build

### PR DESCRIPTION
**Pull request by newffy**

### CODE REVIEW

**Comment by hamnis** [comment]
Cool. now I just need to you to squash ed28bfd, 4d6a3fa and f7ff272 to a new commit.

**Comment by newffy** [comment]
https://github.com/newffy/sbt-aether-deploy/commit/6b87265c8dee6854e81ba581d341d8596c01a428
is ok? Should I do pull request?

**Comment by hamnis** [comment]
6b87265 looks fine. If you dont know how to squash commits, I can do a manual merge and you will still be referenced as author.

**Comment by newffy** [comment]
Great.
At all I don't care about authority, I'm just using your plugin.

2015-08-18 18:02 GMT+03:00 Erlend Hamnaberg <notifications@github.com>:

**Comment by hamnis** [comment]
Merged

**Pull request closed without merging**
